from dotenv import load_dotenv
import os

load_dotenv()

MILVUS_URI = os.getenv("MILVUS_URI")
MILVUS_ADMIN_TOKEN = os.getenv("MILVUS_ADMIN_TOKEN")
MILVUS_COLLECTION_NAME = os.getenv("MILVUS_COLLECTION_NAME")
MILVUS_USERNAME = os.getenv("MILVUS_USERNAME")
MILVUS_PASSWORD = os.getenv("MILVUS_PASSWORD")
MILVUS_ROLE_NAME = os.getenv("MILVUS_ROLE_NAME")
MILVUS_VECTOR_DIM = os.getenv("MILVUS_VECTOR_DIM")
MILVUS_PK_FIELD = os.getenv("MILVUS_PK_FIELD")
MILVUS_EMBEDDING_FIELD = os.getenv("MILVUS_EMBEDDING_FIELD")
MILVUS_TEXT_FIELD = os.getenv("MILVUS_TEXT_FIELD")
